require:
  - rubocop-rspec
  - rubocop-performance

AllCops:
  NewCops: enable
  SuggestExtensions: false
  TargetRubyVersion: 2.4

RSpec/NestedGroups:
  Enabled: true
  Max: 5

Style/Documentation:
  Enabled: false
